name: Build and deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout the repo'
        uses: actions/checkout@v3

      - name: 'Login to GHCR'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: 'Build image '
        run: |
          docker build . --tag ghcr.io/${{ github.actor }}/01-01-scratch:latest
          docker push ghcr.io/${{ github.actor }}/01-01-scratch:latest
